### ISSUE TITLE
Finance bijwerken

### ISSUE THREAD

**Issue by bjorn-out** [uva/webprogrammeren#8]
Zie ook [minprog/cs50x#51](https://github.com/minprog/cs50x/pull/51).

Finance bijwerken om gebruik van cs50 > 5.0.0 mogelijk te maken.

**Comment by Jelleas** [comment]
Geldt dit ook voor github.com/cs50/problems?

**Comment by bjorn-out** [comment]
Waarschijnlijk wel. Zodra je iets met de database deed, deden veel Flask routes het niet meer. Maar ik zie dat dit al is opgelost in 5.0.2.
